# Generated by Django 4.1.5 on 2023-02-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='userprofilepicture',
            field=models.ImageField(upload_to='profile/'),
        ),
    ]
