# Generated by Django 4.1.5 on 2023-02-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styleservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stylistmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sylist_picture', models.ImageField(upload_to='stylist/')),
                ('stylist', models.CharField(max_length=50)),
            ],
        ),
    ]
