# Generated by Django 4.1.5 on 2023-02-21 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('styleservice', '0002_stylistmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookmodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], max_length=100)),
                ('service_Time', models.DateTimeField()),
                ('amount', models.CharField(max_length=99999999)),
                ('additional_info', models.CharField(max_length=1000)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='styleservice.servicemodel')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='styleservice.stylemodel')),
                ('stylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='styleservice.stylistmodel')),
                ('user_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
