# Generated by Django 4.1.5 on 2023-02-19 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('phoneverificationapp', '0002_phonenumbermodel_verifiednumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumbermodel',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
