# Generated by Django 4.1.5 on 2023-03-10 05:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraservices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_supportmodel',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 10, 6, 22, 16, 720470)),
        ),
        migrations.AlterField(
            model_name='idea_suggestionmodel',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 10, 6, 22, 16, 720470)),
        ),
    ]
